version = 1

[merge]
delete_branch_on_merge = true
require_automerge_label = false

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]

[update]
always = true # default: false
require_automerge_label = false # default: true

# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
ignored_usernames = ["dependabot"]
